package `in`.jphe.storyvox.llm.provider

import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Parser tests run against a captured-shape Bedrock streaming
 * response. The bytes were generated by re-encoding three frames
 * (two `contentBlockDelta` and one `messageStop`) with the same frame
 * layout AWS sends. Hex captured by the same Python encoder used in
 * `cloud-chat-assistant/llm_stream.py` so we test the actual parser
 * path rather than a parser-friendly synthetic shape.
 */
class EventStreamParserTest {

    private val json = Json { ignoreUnknownKeys = true }

    /** Three concatenated frames:
     *  - contentBlockDelta { delta: { text: "Hello, " } }
     *  - contentBlockDelta { delta: { text: "world." } }
     *  - messageStop { stopReason: "end_turn" }
     *
     *  Generated by the matching Python encoder; see commit history. */
    private val golden: ByteArray = hexToBytes(
        "0000009d00000057000000000d3a6d6573736167652d747970650700056576656e74" +
            "0b3a6576656e742d74797065070011636f6e74656e74426c6f636b44656c7461" +
            "0d3a636f6e74656e742d747970650700106170706c69636174696f6e2f6a736f6e" +
            "7b22636f6e74656e74426c6f636b496e646578223a20302c202264656c7461223a" +
            "207b2274657874223a202248656c6c6f2c20227d7d00000000" +
            "0000009c00000057000000000d3a6d6573736167652d747970650700056576656e74" +
            "0b3a6576656e742d74797065070011636f6e74656e74426c6f636b44656c7461" +
            "0d3a636f6e74656e742d747970650700106170706c69636174696f6e2f6a736f6e" +
            "7b22636f6e74656e74426c6f636b496e646578223a20302c202264656c7461223a" +
            "207b2274657874223a2022776f726c642e227d7d00000000" +
            "0000007b00000051000000000d3a6d6573736167652d747970650700056576656e74" +
            "0b3a6576656e742d7479706507000b6d65737361676553746f70" +
            "0d3a636f6e74656e742d747970650700106170706c69636174696f6e2f6a736f6e" +
            "7b2273746f70526561736f6e223a2022656e645f7475726e227d00000000",
    )

    @Test
    fun `decode yields all frames in order`() {
        val (events, consumed) = EventStreamParser.decode(golden, json)
        assertEquals(golden.size, consumed)
        assertEquals(3, events.size)
        assertEquals("contentBlockDelta", events[0].eventType)
        assertEquals("contentBlockDelta", events[1].eventType)
        assertEquals("messageStop", events[2].eventType)
    }

    @Test
    fun `decodeTokens returns text deltas only`() {
        val (tokens, consumed) = EventStreamParser.decodeTokens(golden, json)
        assertEquals(listOf("Hello, ", "world."), tokens)
        assertEquals(golden.size, consumed)
    }

    @Test
    fun `partial trailing frame leaves remainder unconsumed`() {
        // Truncate the third frame mid-payload — parser should drain the
        // first two and leave the prefix-of-frame-3 bytes for the next chunk.
        val firstTwoEnd = 157 + 156
        val truncated = golden.copyOf(firstTwoEnd + 20)
        val (tokens, consumed) = EventStreamParser.decodeTokens(truncated, json)
        assertEquals(listOf("Hello, ", "world."), tokens)
        assertEquals(firstTwoEnd, consumed)
        // Caller would keep `truncated.copyOfRange(consumed, truncated.size)`
        // for the next chunk's accumulator.
        assertTrue(truncated.size - consumed > 0)
    }

    @Test
    fun `chunk smaller than 12 byte prelude yields nothing`() {
        val (tokens, consumed) = EventStreamParser.decodeTokens(
            golden.copyOf(8), json,
        )
        assertTrue(tokens.isEmpty())
        assertEquals(0, consumed)
    }

    @Test
    fun `byte-by-byte streaming reconstructs full token list`() {
        // Simulates what the real OkHttp loop does: append small slices,
        // drain anything complete, repeat.
        var buf = ByteArray(0)
        val out = mutableListOf<String>()
        for (b in golden) {
            buf = buf + byteArrayOf(b)
            val (tokens, consumed) = EventStreamParser.decodeTokens(buf, json)
            out.addAll(tokens)
            if (consumed > 0) {
                buf = if (consumed >= buf.size) ByteArray(0)
                else buf.copyOfRange(consumed, buf.size)
            }
        }
        assertEquals(listOf("Hello, ", "world."), out)
    }

    private fun hexToBytes(s: String): ByteArray {
        require(s.length % 2 == 0)
        return ByteArray(s.length / 2) { i ->
            ((Character.digit(s[i * 2], 16) shl 4) +
                Character.digit(s[i * 2 + 1], 16)).toByte()
        }
    }
}
