package `in`.jphe.storyvox.playback.voice

/**
 * Voice catalog: all English Piper voices from rhasspy/piper-voices on
 * huggingface (37 entries) plus all 53 Kokoro speakers from the multi-lang
 * v1.0 model.
 *
 * Piper URL pattern (rhasspy/piper-voices):
 *   .../resolve/main/{family}/{lang_country}/{voice}/{quality}/{voice}.onnx
 *   .../resolve/main/{family}/{lang_country}/{voice}/{quality}/{voice}.onnx.json
 *
 * Kokoro speakers don't have per-voice download URLs — they're indices into
 * the shared kokoro-multi-lang-v1_0 model. The shared model install flow is
 * v0.4.x work; until then Kokoro entries surface with sizeBytes=0 and
 * playback through them returns PlaybackError.EngineUnavailable.
 *
 * Generated; do not hand-edit. Re-run scripts/regen-voice-catalog.py if the
 * upstream voices.json or KokoroVoiceHelper changes.
 */
object VoiceCatalog {

    val voices: List<CatalogEntry> = listOf(
        // ----- Piper voices (English; full rhasspy/piper-voices catalog) -----
        CatalogEntry(
            id = "piper_alan_en_GB_low",
            displayName = "Alan (Low)",
            language = "en_GB",
            sizeBytes = 63104526L,
            qualityLevel = QualityLevel.Low,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/alan/low/en_GB-alan-low.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/alan/low/en_GB-alan-low.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_alan_en_GB_medium",
            displayName = "Alan (Medium)",
            language = "en_GB",
            sizeBytes = 63201294L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/alan/medium/en_GB-alan-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/alan/medium/en_GB-alan-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_alba_en_GB_medium",
            displayName = "Alba (Medium)",
            language = "en_GB",
            sizeBytes = 63201294L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/alba/medium/en_GB-alba-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/alba/medium/en_GB-alba-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_aru_en_GB_medium",
            displayName = "Aru (Medium)",
            language = "en_GB",
            sizeBytes = 76754097L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/aru/medium/en_GB-aru-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/aru/medium/en_GB-aru-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_cori_en_GB_medium",
            displayName = "Cori (Medium)",
            language = "en_GB",
            sizeBytes = 63531379L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/cori/medium/en_GB-cori-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/cori/medium/en_GB-cori-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_cori_en_GB_high",
            displayName = "Cori (High)",
            language = "en_GB",
            sizeBytes = 114219352L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/cori/high/en_GB-cori-high.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/cori/high/en_GB-cori-high.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_jenny_dioco_en_GB_medium",
            displayName = "Jenny Dioco (Medium)",
            language = "en_GB",
            sizeBytes = 63201294L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/jenny_dioco/medium/en_GB-jenny_dioco-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/jenny_dioco/medium/en_GB-jenny_dioco-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_northern_english_male_en_GB_medium",
            displayName = "Northern English Male (Medium)",
            language = "en_GB",
            sizeBytes = 63201294L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/northern_english_male/medium/en_GB-northern_english_male-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/northern_english_male/medium/en_GB-northern_english_male-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_semaine_en_GB_medium",
            displayName = "Semaine (Medium)",
            language = "en_GB",
            sizeBytes = 76737711L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/semaine/medium/en_GB-semaine-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/semaine/medium/en_GB-semaine-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_southern_english_female_en_GB_low",
            displayName = "Southern English Female (Low)",
            language = "en_GB",
            sizeBytes = 63104526L,
            qualityLevel = QualityLevel.Low,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/southern_english_female/low/en_GB-southern_english_female-low.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/southern_english_female/low/en_GB-southern_english_female-low.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_vctk_en_GB_medium",
            displayName = "Vctk (Medium)",
            language = "en_GB",
            sizeBytes = 76952753L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/vctk/medium/en_GB-vctk-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_GB/vctk/medium/en_GB-vctk-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_amy_en_US_low",
            displayName = "Amy (Low)",
            language = "en_US",
            sizeBytes = 63104526L,
            qualityLevel = QualityLevel.Low,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/low/en_US-amy-low.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/low/en_US-amy-low.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_amy_en_US_medium",
            displayName = "Amy (Medium)",
            language = "en_US",
            sizeBytes = 63201294L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/en_US-amy-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/amy/medium/en_US-amy-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_arctic_en_US_medium",
            displayName = "Arctic (Medium)",
            language = "en_US",
            sizeBytes = 76766385L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/arctic/medium/en_US-arctic-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/arctic/medium/en_US-arctic-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_bryce_en_US_medium",
            displayName = "Bryce (Medium)",
            language = "en_US",
            sizeBytes = 63531379L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/bryce/medium/en_US-bryce-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/bryce/medium/en_US-bryce-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_danny_en_US_low",
            displayName = "Danny (Low)",
            language = "en_US",
            sizeBytes = 63104526L,
            qualityLevel = QualityLevel.Low,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/danny/low/en_US-danny-low.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/danny/low/en_US-danny-low.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_hfc_female_en_US_medium",
            displayName = "Hfc Female (Medium)",
            language = "en_US",
            sizeBytes = 63201294L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/hfc_female/medium/en_US-hfc_female-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/hfc_female/medium/en_US-hfc_female-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_hfc_male_en_US_medium",
            displayName = "Hfc Male (Medium)",
            language = "en_US",
            sizeBytes = 63201294L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/hfc_male/medium/en_US-hfc_male-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/hfc_male/medium/en_US-hfc_male-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_joe_en_US_medium",
            displayName = "Joe (Medium)",
            language = "en_US",
            sizeBytes = 63201294L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/joe/medium/en_US-joe-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/joe/medium/en_US-joe-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_john_en_US_medium",
            displayName = "John (Medium)",
            language = "en_US",
            sizeBytes = 63531379L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/john/medium/en_US-john-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/john/medium/en_US-john-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_kathleen_en_US_low",
            displayName = "Kathleen (Low)",
            language = "en_US",
            sizeBytes = 63104526L,
            qualityLevel = QualityLevel.Low,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/kathleen/low/en_US-kathleen-low.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/kathleen/low/en_US-kathleen-low.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_kristin_en_US_medium",
            displayName = "Kristin (Medium)",
            language = "en_US",
            sizeBytes = 63531379L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/kristin/medium/en_US-kristin-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/kristin/medium/en_US-kristin-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_kusal_en_US_medium",
            displayName = "Kusal (Medium)",
            language = "en_US",
            sizeBytes = 63201294L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/kusal/medium/en_US-kusal-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/kusal/medium/en_US-kusal-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_l2arctic_en_US_medium",
            displayName = "L2Arctic (Medium)",
            language = "en_US",
            sizeBytes = 76778673L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/l2arctic/medium/en_US-l2arctic-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/l2arctic/medium/en_US-l2arctic-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_lessac_en_US_low",
            displayName = "Lessac (Low)",
            language = "en_US",
            sizeBytes = 63201294L,
            qualityLevel = QualityLevel.Low,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/low/en_US-lessac-low.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/low/en_US-lessac-low.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_lessac_en_US_medium",
            displayName = "Lessac (Medium)",
            language = "en_US",
            sizeBytes = 63201294L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_lessac_en_US_high",
            displayName = "Lessac (High)",
            language = "en_US",
            sizeBytes = 113895201L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/high/en_US-lessac-high.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/high/en_US-lessac-high.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_libritts_en_US_high",
            displayName = "Libritts (High)",
            language = "en_US",
            sizeBytes = 136673811L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts/high/en_US-libritts-high.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts/high/en_US-libritts-high.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_libritts_r_en_US_medium",
            displayName = "Libritts R (Medium)",
            language = "en_US",
            sizeBytes = 78580914L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_ljspeech_en_US_medium",
            displayName = "Ljspeech (Medium)",
            language = "en_US",
            sizeBytes = 63531379L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ljspeech/medium/en_US-ljspeech-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ljspeech/medium/en_US-ljspeech-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_ljspeech_en_US_high",
            displayName = "Ljspeech (High)",
            language = "en_US",
            sizeBytes = 114199011L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ljspeech/high/en_US-ljspeech-high.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ljspeech/high/en_US-ljspeech-high.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_norman_en_US_medium",
            displayName = "Norman (Medium)",
            language = "en_US",
            sizeBytes = 63531379L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/norman/medium/en_US-norman-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/norman/medium/en_US-norman-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_reza_ibrahim_en_US_medium",
            displayName = "Reza Ibrahim (Medium)",
            language = "en_US",
            sizeBytes = 63511038L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/reza_ibrahim/medium/en_US-reza_ibrahim-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/reza_ibrahim/medium/en_US-reza_ibrahim-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_ryan_en_US_low",
            displayName = "Ryan (Low)",
            language = "en_US",
            sizeBytes = 63104526L,
            qualityLevel = QualityLevel.Low,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/low/en_US-ryan-low.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/low/en_US-ryan-low.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_ryan_en_US_medium",
            displayName = "Ryan (Medium)",
            language = "en_US",
            sizeBytes = 63201294L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/medium/en_US-ryan-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/medium/en_US-ryan-medium.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_ryan_en_US_high",
            displayName = "Ryan (High)",
            language = "en_US",
            sizeBytes = 120786792L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/high/en_US-ryan-high.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/ryan/high/en_US-ryan-high.onnx.json",
            ),
        ),
        CatalogEntry(
            id = "piper_sam_en_US_medium",
            displayName = "Sam (Medium)",
            language = "en_US",
            sizeBytes = 62950044L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/sam/medium/en_US-sam-medium.onnx",
                tokensUrl = "https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/sam/medium/en_US-sam-medium.onnx.json",
            ),
        ),

        // ----- Kokoro speakers (53 from kokoro-multi-lang-v1_0, no per-voice download) -----
        CatalogEntry(
            id = "kokoro_alloy_en_US_0",
            displayName = "🇺🇸 Alloy (English Female)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 0),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_aoede_en_US_1",
            displayName = "🇺🇸 Aoede (English Female)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 1),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_bella_en_US_2",
            displayName = "🇺🇸 Bella (English Female)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 2),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_heart_en_US_3",
            displayName = "🇺🇸 Heart (English Female)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 3),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_jessica_en_US_4",
            displayName = "🇺🇸 Jessica (English Female)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 4),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_kore_en_US_5",
            displayName = "🇺🇸 Kore (English Female)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 5),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_nicole_en_US_6",
            displayName = "🇺🇸 Nicole (English Female)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 6),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_nova_en_US_7",
            displayName = "🇺🇸 Nova (English Female)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 7),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_river_en_US_8",
            displayName = "🇺🇸 River (English Female)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 8),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_sarah_en_US_9",
            displayName = "🇺🇸 Sarah (English Female)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 9),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_sky_en_US_10",
            displayName = "🇺🇸 Sky (English Female)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 10),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_adam_en_US_11",
            displayName = "🇺🇸 Adam (English Male)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 11),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_echo_en_US_12",
            displayName = "🇺🇸 Echo (English Male)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 12),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_eric_en_US_13",
            displayName = "🇺🇸 Eric (English Male)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 13),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_fenrir_en_US_14",
            displayName = "🇺🇸 Fenrir (English Male)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 14),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_liam_en_US_15",
            displayName = "🇺🇸 Liam (English Male)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 15),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_michael_en_US_16",
            displayName = "🇺🇸 Michael (English Male)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 16),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_onyx_en_US_17",
            displayName = "🇺🇸 Onyx (English Male)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 17),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_puck_en_US_18",
            displayName = "🇺🇸 Puck (English Male)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 18),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_santa_en_US_19",
            displayName = "🇺🇸 Santa (English Male)",
            language = "en_US",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 19),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_alice_en_GB_20",
            displayName = "🇬🇧 Alice (English Female)",
            language = "en_GB",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 20),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_emma_en_GB_21",
            displayName = "🇬🇧 Emma (English Female)",
            language = "en_GB",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 21),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_isabella_en_GB_22",
            displayName = "🇬🇧 Isabella (English Female)",
            language = "en_GB",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 22),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_lily_en_GB_23",
            displayName = "🇬🇧 Lily (English Female)",
            language = "en_GB",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 23),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_daniel_en_GB_24",
            displayName = "🇬🇧 Daniel (English Male)",
            language = "en_GB",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 24),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_fable_en_GB_25",
            displayName = "🇬🇧 Fable (English Male)",
            language = "en_GB",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 25),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_george_en_GB_26",
            displayName = "🇬🇧 George (English Male)",
            language = "en_GB",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 26),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_lewis_en_GB_27",
            displayName = "🇬🇧 Lewis (English Male)",
            language = "en_GB",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 27),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_dora_es_ES_28",
            displayName = "🇪🇸 Dora (Spanish Female)",
            language = "es_ES",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 28),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_alex_es_ES_29",
            displayName = "🇪🇸 Alex (Spanish Male)",
            language = "es_ES",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 29),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_siwis_fr_FR_30",
            displayName = "🇫🇷 Siwis (French Female)",
            language = "fr_FR",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 30),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_alpha_hi_IN_31",
            displayName = "🇮🇳 Alpha (Hindi Female)",
            language = "hi_IN",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 31),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_beta_hi_IN_32",
            displayName = "🇮🇳 Beta (Hindi Female)",
            language = "hi_IN",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 32),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_omega_hi_IN_33",
            displayName = "🇮🇳 Omega (Hindi Male)",
            language = "hi_IN",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 33),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_psi_hi_IN_34",
            displayName = "🇮🇳 Psi (Hindi Male)",
            language = "hi_IN",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 34),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_sara_it_IT_35",
            displayName = "🇮🇹 Sara (Italian Female)",
            language = "it_IT",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 35),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_nicola_it_IT_36",
            displayName = "🇮🇹 Nicola (Italian Male)",
            language = "it_IT",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 36),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_alpha_ja_JP_37",
            displayName = "🇯🇵 Alpha (Japanese Female)",
            language = "ja_JP",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 37),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_gongitsune_ja_JP_38",
            displayName = "🇯🇵 Gongitsune (Japanese Female)",
            language = "ja_JP",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 38),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_nezumi_ja_JP_39",
            displayName = "🇯🇵 Nezumi (Japanese Female)",
            language = "ja_JP",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 39),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_tebukuro_ja_JP_40",
            displayName = "🇯🇵 Tebukuro (Japanese Female)",
            language = "ja_JP",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 40),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_kumo_ja_JP_41",
            displayName = "🇯🇵 Kumo (Japanese Male)",
            language = "ja_JP",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 41),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_dora_pt_PT_42",
            displayName = "🇵🇹 Dora (Portuguese Female)",
            language = "pt_PT",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 42),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_alex_pt_PT_43",
            displayName = "🇵🇹 Alex (Portuguese Male)",
            language = "pt_PT",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 43),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_santa_pt_PT_44",
            displayName = "🇵🇹 Santa (Portuguese Male)",
            language = "pt_PT",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 44),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_xiaobei_zh_CN_45",
            displayName = "🇨🇳 Xiaobei (Chinese Female)",
            language = "zh_CN",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 45),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_xiaoni_zh_CN_46",
            displayName = "🇨🇳 Xiaoni (Chinese Female)",
            language = "zh_CN",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 46),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_xiaoxiao_zh_CN_47",
            displayName = "🇨🇳 Xiaoxiao (Chinese Female)",
            language = "zh_CN",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 47),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_xiaoyi_zh_CN_48",
            displayName = "🇨🇳 Xiaoyi (Chinese Female)",
            language = "zh_CN",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 48),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_yunjian_zh_CN_49",
            displayName = "🇨🇳 Yunjian (Chinese Male)",
            language = "zh_CN",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 49),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_yunxi_zh_CN_50",
            displayName = "🇨🇳 Yunxi (Chinese Male)",
            language = "zh_CN",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 50),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_yunxia_zh_CN_51",
            displayName = "🇨🇳 Yunxia (Chinese Male)",
            language = "zh_CN",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 51),
            piper = null,
        ),
        CatalogEntry(
            id = "kokoro_yunyang_zh_CN_52",
            displayName = "🇨🇳 Yunyang (Chinese Male)",
            language = "zh_CN",
            sizeBytes = 0L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Kokoro(speakerId = 52),
            piper = null,
        ),
    )

    fun byId(id: String): CatalogEntry? = voices.firstOrNull { it.id == id }
}

/**
 * Catalog entry — adds provisioning fields ([piper] URLs) on top of the
 * UI-facing [UiVoiceInfo] shape. [VoiceManager] projects this into
 * [UiVoiceInfo] for callers, hiding the URLs from the UI layer.
 */
data class CatalogEntry(
    val id: String,
    val displayName: String,
    val language: String,
    val sizeBytes: Long,
    val qualityLevel: QualityLevel,
    val engineType: EngineType,
    /** Non-null only for Piper entries. */
    val piper: PiperPaths?,
)

data class PiperPaths(val onnxUrl: String, val tokensUrl: String)

