package `in`.jphe.storyvox.playback.voice

object VoiceCatalog {
    val voices: List<CatalogEntry> = piperEntries() + kokoroEntries()
    fun byId(id: String): CatalogEntry? = voices.firstOrNull { it.id == id }
    private fun piperEntries(): List<CatalogEntry> = listOf(
        CatalogEntry(
            id = "piper_lessac_en_US_high_int8",
            displayName = "⭐ Lessac (High)",
            language = "en_US",
            sizeBytes = 35022847L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/lessac-high-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/lessac-high-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_ryan_en_US_high_int8",
            displayName = "⭐ Ryan (High)",
            language = "en_US",
            sizeBytes = 34473341L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/ryan-high-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/ryan-high-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_amy_en_US_medium_int8",
            displayName = "⭐ Amy (Medium)",
            language = "en_US",
            sizeBytes = 21028122L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/amy-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/amy-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_alan_en_GB_low_int8",
            displayName = "Alan (Low)",
            language = "en_GB",
            sizeBytes = 21289969L,
            qualityLevel = QualityLevel.Low,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/alan-low-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/alan-low-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_alan_en_GB_medium_int8",
            displayName = "Alan (Medium)",
            language = "en_GB",
            sizeBytes = 21103831L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/alan-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/alan-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_alba_en_GB_medium_int8",
            displayName = "Alba (Medium)",
            language = "en_GB",
            sizeBytes = 21104326L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/alba-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/alba-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_aru_en_GB_medium_int8",
            displayName = "Aru (Medium)",
            language = "en_GB",
            sizeBytes = 23125986L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/aru-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/aru-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_cori_en_GB_medium_int8",
            displayName = "Cori (Medium)",
            language = "en_GB",
            sizeBytes = 20768736L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/cori-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/cori-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_cori_en_GB_high_int8",
            displayName = "Cori (High)",
            language = "en_GB",
            sizeBytes = 35038210L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/cori-high-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/cori-high-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_dii_en_GB_high_int8",
            displayName = "Dii (High)",
            language = "en_GB",
            sizeBytes = 21037620L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/dii-high-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/dii-high-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_jenny_dioco_en_GB_medium_int8",
            displayName = "Jenny Dioco (Medium)",
            language = "en_GB",
            sizeBytes = 20950036L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/jenny_dioco-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/jenny_dioco-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_miro_en_GB_high_int8",
            displayName = "Miro (High)",
            language = "en_GB",
            sizeBytes = 21347062L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/miro-high-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/miro-high-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_northern_english_male_en_GB_medium_int8",
            displayName = "Northern English Male (Medium)",
            language = "en_GB",
            sizeBytes = 21100291L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/northern_english_male-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/northern_english_male-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_semaine_en_GB_medium_int8",
            displayName = "Semaine (Medium)",
            language = "en_GB",
            sizeBytes = 23227810L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/semaine-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/semaine-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_southern_english_female_en_GB_low_int8",
            displayName = "Southern English Female (Low)",
            language = "en_GB",
            sizeBytes = 21207615L,
            qualityLevel = QualityLevel.Low,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/southern_english_female-low-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/southern_english_female-low-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_southern_english_female_en_GB_medium_int8",
            displayName = "Southern English Female (Medium)",
            language = "en_GB",
            sizeBytes = 23714066L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/southern_english_female-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/southern_english_female-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_southern_english_male_en_GB_medium_int8",
            displayName = "Southern English Male (Medium)",
            language = "en_GB",
            sizeBytes = 23601346L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/southern_english_male-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/southern_english_male-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_vctk_en_GB_medium_int8",
            displayName = "Vctk (Medium)",
            language = "en_GB",
            sizeBytes = 23366127L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/vctk-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/vctk-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_amy_en_US_low_int8",
            displayName = "Amy (Low)",
            language = "en_US",
            sizeBytes = 21099246L,
            qualityLevel = QualityLevel.Low,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/amy-low-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/amy-low-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_arctic_en_US_medium_int8",
            displayName = "Arctic (Medium)",
            language = "en_US",
            sizeBytes = 23320524L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/arctic-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/arctic-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_bryce_en_US_medium_int8",
            displayName = "Bryce (Medium)",
            language = "en_US",
            sizeBytes = 20910568L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/bryce-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/bryce-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_danny_en_US_low_int8",
            displayName = "Danny (Low)",
            language = "en_US",
            sizeBytes = 21184916L,
            qualityLevel = QualityLevel.Low,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/danny-low-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/danny-low-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_glados_en_US_high_int8",
            displayName = "Glados (High)",
            language = "en_US",
            sizeBytes = 35125025L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/glados-high-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/glados-high-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_hfc_female_en_US_medium_int8",
            displayName = "Hfc Female (Medium)",
            language = "en_US",
            sizeBytes = 21021379L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/hfc_female-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/hfc_female-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_hfc_male_en_US_medium_int8",
            displayName = "Hfc Male (Medium)",
            language = "en_US",
            sizeBytes = 20984819L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/hfc_male-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/hfc_male-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_joe_en_US_medium_int8",
            displayName = "Joe (Medium)",
            language = "en_US",
            sizeBytes = 21230019L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/joe-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/joe-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_john_en_US_medium_int8",
            displayName = "John (Medium)",
            language = "en_US",
            sizeBytes = 20800096L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/john-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/john-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_kathleen_en_US_low_int8",
            displayName = "Kathleen (Low)",
            language = "en_US",
            sizeBytes = 21289266L,
            qualityLevel = QualityLevel.Low,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/kathleen-low-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/kathleen-low-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_kristin_en_US_medium_int8",
            displayName = "Kristin (Medium)",
            language = "en_US",
            sizeBytes = 20882061L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/kristin-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/kristin-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_kusal_en_US_medium_int8",
            displayName = "Kusal (Medium)",
            language = "en_US",
            sizeBytes = 21044470L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/kusal-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/kusal-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_l2arctic_en_US_medium_int8",
            displayName = "L2Arctic (Medium)",
            language = "en_US",
            sizeBytes = 23273574L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/l2arctic-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/l2arctic-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_lessac_en_US_low_int8",
            displayName = "Lessac (Low)",
            language = "en_US",
            sizeBytes = 21070568L,
            qualityLevel = QualityLevel.Low,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/lessac-low-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/lessac-low-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_lessac_en_US_medium_int8",
            displayName = "Lessac (Medium)",
            language = "en_US",
            sizeBytes = 20969179L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/lessac-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/lessac-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_libritts_en_US_high_int8",
            displayName = "Libritts (High)",
            language = "en_US",
            sizeBytes = 36406088L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/libritts-high-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/libritts-high-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_libritts_r_en_US_medium_int8",
            displayName = "Libritts R (Medium)",
            language = "en_US",
            sizeBytes = 23398348L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/libritts_r-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/libritts_r-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_ljspeech_en_US_medium_int8",
            displayName = "Ljspeech (Medium)",
            language = "en_US",
            sizeBytes = 21090429L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/ljspeech-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/ljspeech-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_ljspeech_en_US_high_int8",
            displayName = "Ljspeech (High)",
            language = "en_US",
            sizeBytes = 33886472L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/ljspeech-high-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/ljspeech-high-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_miro_en_US_high_int8",
            displayName = "Miro (High)",
            language = "en_US",
            sizeBytes = 21336806L,
            qualityLevel = QualityLevel.High,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/miro-high-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/miro-high-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_norman_en_US_medium_int8",
            displayName = "Norman (Medium)",
            language = "en_US",
            sizeBytes = 20987233L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/norman-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/norman-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_reza_ibrahim_en_US_medium_int8",
            displayName = "Reza Ibrahim (Medium)",
            language = "en_US",
            sizeBytes = 21139277L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/reza_ibrahim-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/reza_ibrahim-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_ryan_en_US_low_int8",
            displayName = "Ryan (Low)",
            language = "en_US",
            sizeBytes = 21212659L,
            qualityLevel = QualityLevel.Low,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/ryan-low-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/ryan-low-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_ryan_en_US_medium_int8",
            displayName = "Ryan (Medium)",
            language = "en_US",
            sizeBytes = 21083446L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/ryan-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/ryan-medium-int8.tokens.txt",
            ),
        ),
        CatalogEntry(
            id = "piper_sam_en_US_medium_int8",
            displayName = "Sam (Medium)",
            language = "en_US",
            sizeBytes = 20874946L,
            qualityLevel = QualityLevel.Medium,
            engineType = EngineType.Piper,
            piper = PiperPaths(
                onnxUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/sam-medium-int8.onnx",
                tokensUrl = "https://github.com/jphein/VoxSherpa-TTS/releases/download/voices-v1/sam-medium-int8.tokens.txt",
            ),
        ),
    )

    private fun kokoroEntries(): List<CatalogEntry> = listOf(
        CatalogEntry(id = "kokoro_alloy_en_US_0", displayName = "🇺🇸 Alloy (English Female · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 0), piper = null),
        CatalogEntry(id = "kokoro_aoede_en_US_1", displayName = "🇺🇸 Aoede (English Female · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 1), piper = null),
        CatalogEntry(id = "kokoro_bella_en_US_2", displayName = "🇺🇸 Bella (English Female · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 2), piper = null),
        CatalogEntry(id = "kokoro_heart_en_US_3", displayName = "🇺🇸 Heart (English Female · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 3), piper = null),
        CatalogEntry(id = "kokoro_jessica_en_US_4", displayName = "🇺🇸 Jessica (English Female · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 4), piper = null),
        CatalogEntry(id = "kokoro_kore_en_US_5", displayName = "🇺🇸 Kore (English Female · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 5), piper = null),
        CatalogEntry(id = "kokoro_nicole_en_US_6", displayName = "🇺🇸 Nicole (English Female · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 6), piper = null),
        CatalogEntry(id = "kokoro_nova_en_US_7", displayName = "🇺🇸 Nova (English Female · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 7), piper = null),
        CatalogEntry(id = "kokoro_river_en_US_8", displayName = "🇺🇸 River (English Female · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 8), piper = null),
        CatalogEntry(id = "kokoro_sarah_en_US_9", displayName = "🇺🇸 Sarah (English Female · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 9), piper = null),
        CatalogEntry(id = "kokoro_sky_en_US_10", displayName = "🇺🇸 Sky (English Female · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 10), piper = null),
        CatalogEntry(id = "kokoro_adam_en_US_11", displayName = "🇺🇸 Adam (English Male · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 11), piper = null),
        CatalogEntry(id = "kokoro_echo_en_US_12", displayName = "🇺🇸 Echo (English Male · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 12), piper = null),
        CatalogEntry(id = "kokoro_eric_en_US_13", displayName = "🇺🇸 Eric (English Male · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 13), piper = null),
        CatalogEntry(id = "kokoro_fenrir_en_US_14", displayName = "🇺🇸 Fenrir (English Male · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 14), piper = null),
        CatalogEntry(id = "kokoro_liam_en_US_15", displayName = "🇺🇸 Liam (English Male · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 15), piper = null),
        CatalogEntry(id = "kokoro_michael_en_US_16", displayName = "🇺🇸 Michael (English Male · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 16), piper = null),
        CatalogEntry(id = "kokoro_onyx_en_US_17", displayName = "🇺🇸 Onyx (English Male · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 17), piper = null),
        CatalogEntry(id = "kokoro_puck_en_US_18", displayName = "🇺🇸 Puck (English Male · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 18), piper = null),
        CatalogEntry(id = "kokoro_santa_en_US_19", displayName = "🇺🇸 Santa (English Male · coming soon)", language = "en_US", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 19), piper = null),
        CatalogEntry(id = "kokoro_alice_en_GB_20", displayName = "🇬🇧 Alice (English Female · coming soon)", language = "en_GB", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 20), piper = null),
        CatalogEntry(id = "kokoro_emma_en_GB_21", displayName = "🇬🇧 Emma (English Female · coming soon)", language = "en_GB", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 21), piper = null),
        CatalogEntry(id = "kokoro_isabella_en_GB_22", displayName = "🇬🇧 Isabella (English Female · coming soon)", language = "en_GB", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 22), piper = null),
        CatalogEntry(id = "kokoro_lily_en_GB_23", displayName = "🇬🇧 Lily (English Female · coming soon)", language = "en_GB", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 23), piper = null),
        CatalogEntry(id = "kokoro_daniel_en_GB_24", displayName = "🇬🇧 Daniel (English Male · coming soon)", language = "en_GB", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 24), piper = null),
        CatalogEntry(id = "kokoro_fable_en_GB_25", displayName = "🇬🇧 Fable (English Male · coming soon)", language = "en_GB", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 25), piper = null),
        CatalogEntry(id = "kokoro_george_en_GB_26", displayName = "🇬🇧 George (English Male · coming soon)", language = "en_GB", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 26), piper = null),
        CatalogEntry(id = "kokoro_lewis_en_GB_27", displayName = "🇬🇧 Lewis (English Male · coming soon)", language = "en_GB", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 27), piper = null),
        CatalogEntry(id = "kokoro_dora_es_ES_28", displayName = "🇪🇸 Dora (Spanish Female · coming soon)", language = "es_ES", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 28), piper = null),
        CatalogEntry(id = "kokoro_alex_es_ES_29", displayName = "🇪🇸 Alex (Spanish Male · coming soon)", language = "es_ES", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 29), piper = null),
        CatalogEntry(id = "kokoro_siwis_fr_FR_30", displayName = "🇫🇷 Siwis (French Female · coming soon)", language = "fr_FR", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 30), piper = null),
        CatalogEntry(id = "kokoro_alpha_hi_IN_31", displayName = "🇮🇳 Alpha (Hindi Female · coming soon)", language = "hi_IN", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 31), piper = null),
        CatalogEntry(id = "kokoro_beta_hi_IN_32", displayName = "🇮🇳 Beta (Hindi Female · coming soon)", language = "hi_IN", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 32), piper = null),
        CatalogEntry(id = "kokoro_omega_hi_IN_33", displayName = "🇮🇳 Omega (Hindi Male · coming soon)", language = "hi_IN", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 33), piper = null),
        CatalogEntry(id = "kokoro_psi_hi_IN_34", displayName = "🇮🇳 Psi (Hindi Male · coming soon)", language = "hi_IN", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 34), piper = null),
        CatalogEntry(id = "kokoro_sara_it_IT_35", displayName = "🇮🇹 Sara (Italian Female · coming soon)", language = "it_IT", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 35), piper = null),
        CatalogEntry(id = "kokoro_nicola_it_IT_36", displayName = "🇮🇹 Nicola (Italian Male · coming soon)", language = "it_IT", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 36), piper = null),
        CatalogEntry(id = "kokoro_alpha_ja_JP_37", displayName = "🇯🇵 Alpha (Japanese Female · coming soon)", language = "ja_JP", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 37), piper = null),
        CatalogEntry(id = "kokoro_gongitsune_ja_JP_38", displayName = "🇯🇵 Gongitsune (Japanese Female · coming soon)", language = "ja_JP", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 38), piper = null),
        CatalogEntry(id = "kokoro_nezumi_ja_JP_39", displayName = "🇯🇵 Nezumi (Japanese Female · coming soon)", language = "ja_JP", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 39), piper = null),
        CatalogEntry(id = "kokoro_tebukuro_ja_JP_40", displayName = "🇯🇵 Tebukuro (Japanese Female · coming soon)", language = "ja_JP", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 40), piper = null),
        CatalogEntry(id = "kokoro_kumo_ja_JP_41", displayName = "🇯🇵 Kumo (Japanese Male · coming soon)", language = "ja_JP", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 41), piper = null),
        CatalogEntry(id = "kokoro_dora_pt_PT_42", displayName = "🇵🇹 Dora (Portuguese Female · coming soon)", language = "pt_PT", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 42), piper = null),
        CatalogEntry(id = "kokoro_alex_pt_PT_43", displayName = "🇵🇹 Alex (Portuguese Male · coming soon)", language = "pt_PT", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 43), piper = null),
        CatalogEntry(id = "kokoro_santa_pt_PT_44", displayName = "🇵🇹 Santa (Portuguese Male · coming soon)", language = "pt_PT", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 44), piper = null),
        CatalogEntry(id = "kokoro_xiaobei_zh_CN_45", displayName = "🇨🇳 Xiaobei (Chinese Female · coming soon)", language = "zh_CN", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 45), piper = null),
        CatalogEntry(id = "kokoro_xiaoni_zh_CN_46", displayName = "🇨🇳 Xiaoni (Chinese Female · coming soon)", language = "zh_CN", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 46), piper = null),
        CatalogEntry(id = "kokoro_xiaoxiao_zh_CN_47", displayName = "🇨🇳 Xiaoxiao (Chinese Female · coming soon)", language = "zh_CN", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 47), piper = null),
        CatalogEntry(id = "kokoro_xiaoyi_zh_CN_48", displayName = "🇨🇳 Xiaoyi (Chinese Female · coming soon)", language = "zh_CN", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 48), piper = null),
        CatalogEntry(id = "kokoro_yunjian_zh_CN_49", displayName = "🇨🇳 Yunjian (Chinese Male · coming soon)", language = "zh_CN", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 49), piper = null),
        CatalogEntry(id = "kokoro_yunxi_zh_CN_50", displayName = "🇨🇳 Yunxi (Chinese Male · coming soon)", language = "zh_CN", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 50), piper = null),
        CatalogEntry(id = "kokoro_yunxia_zh_CN_51", displayName = "🇨🇳 Yunxia (Chinese Male · coming soon)", language = "zh_CN", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 51), piper = null),
        CatalogEntry(id = "kokoro_yunyang_zh_CN_52", displayName = "🇨🇳 Yunyang (Chinese Male · coming soon)", language = "zh_CN", sizeBytes = 0L, qualityLevel = QualityLevel.High, engineType = EngineType.Kokoro(speakerId = 52), piper = null),
    )
}

data class CatalogEntry(val id: String, val displayName: String, val language: String, val sizeBytes: Long, val qualityLevel: QualityLevel, val engineType: EngineType, val piper: PiperPaths?)
data class PiperPaths(val onnxUrl: String, val tokensUrl: String)
